name = "ShockWaves"
uuid = "c1695130-2840-4767-8981-aa8d2370ae89"
authors = ["Kevin <9022843+fergu@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
